mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="polls/")),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    """
    Represents a poll question.
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", default=timezone.now)
    end_date = models.DateTimeField("date ended", null=True, blank=True)

    def is_published(self):
        """
        Returns True if the question is published.
        """
        return self.pub_date <= timezone.localtime(timezone.now())

    def can_vote(self):
        """
        Returns True if the question can be voted on.
        """
        return self.pub_date <= timezone.localtime(timezone.now()) \
            and ((self.end_date is None) or
                 (self.end_date > timezone.localtime(timezone.now())))

    def was_published_recently(self):
        """
        Returns True if the question was published within the last day.
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    """
    Represents a choice for a poll question.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    @property
    def votes(self):
        """Return the number count"""
        return self.vote_set.count()

    def __str__(self):
        return self.choice_text


class Vote(models.Model):
    """Record a Vote of a Choice by a User."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} voted for {self.choice}"

mysite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


def signup(request):
    """Register a new user."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # save the new user
            form.save()
            # get named fields from the form data
            username = form.cleaned_data.get('username')
            # password input field is named 'password1'
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            # redirect to home page
            return redirect('polls:index')
    else:
        # create a user form and display it the signup page
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

polls/views.py
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question, Vote


class IndexView(generic.ListView):
    """
    View for the index page.
    """
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()).order_by("-pub_date")


class DetailView(generic.DetailView):
    """
    View for the detail page.
    """
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get(self, request, *args, **kwargs):
        """
        Returns the detail page for a question.
        """
        try:
            question = get_object_or_404(Question, pk=kwargs["pk"])

            if not question.can_vote():
                messages.error(request, "This page doesn't allow voting.")
                return redirect("polls:index")
        except Http404:
            messages.error(request, "This question does not exist.")
            return redirect("polls:index")
        choice_voted = None
        if request.user.is_authenticated:
            try:
                vote = Vote.objects.get(user=request.user,
                                        choice__in=question.choice_set.all())
                choice_voted = vote.choice.choice_text
            except Vote.DoesNotExist:
                choice_voted = None

        return render(request, self.template_name,
                      {"question": question, "choice_voted": choice_voted})


class ResultsView(generic.DetailView):
    """
    View for the results page.
    """
    model = Question
    template_name = "polls/results.html"

    def get(self, request, *args, **kwargs):
        """
        Returns the results page for a question.
        """
        question = get_object_or_404(Question, pk=kwargs["pk"])
        return render(request, self.template_name, {"question": question})


@login_required
def vote(request, question_id):
    """
    Handles voting for a particular choice in a question.
    """
    try:
        question = get_object_or_404(Question, pk=question_id)
    except Http404:
        messages.error(request, "This question does not exist.")
        return redirect("polls:index")

    if not question.can_vote():
        messages.error(request, "This question page not allow voting.")
        return redirect("polls:index")
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "You didn't select a choice.")
        return redirect("polls:detail", question_id)
    this_user = request.user
    try:
        # find a vote by this user for this question
        vote = Vote.objects.get(user=this_user, choice__question=question)
        # update this vote
        vote.choice = selected_choice
    except Vote.DoesNotExist:
        # no matching vote - create a new Vote
        vote = Vote(user=this_user, choice=selected_choice)
    # save the vote
    vote.save()

    # Display a message that the user's vote was successful.
    messages.success(
        request, f"Your vote for {question.question_text} has been saved.")
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Polls</title>{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="icon" href="{% static 'polls/images/favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <nav>
        <div class="logo">
            {% block logo %}<a href="{% url 'polls:index'%}">KU Polls</a>{% endblock %}
        </div>
        <ul class="menu">
            {% block home %}<li><a href="{% url 'polls:index'%}">Home</a></li>{% endblock %}
            {% if user.is_authenticated %}
                {% block logout %}<li><a href="{% url 'logout'%}">Logout</a></li>{% endblock %}
            {% else %}
                {% block signup %}<li><a href="{% url 'signup'%}">Sign up</a></li>{% endblock %}
                {% block login %}<li><a href="{% url 'login'%}">Login</a></li>{% endblock %}
            {% endif %}
        </ul>
    </nav>
    <div class="content">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block title %}<title>Poll Questions</title>{% endblock %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset class="question-box">
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <b><p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p></b>
                {% endfor %}
            </ul>
            {% endif %}
            {% for choice in question.choice_set.all %}
            <div class="choice-box">
                {% if choice.choice_text == choice_voted %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" checked>
                {% else %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                {% endif %}
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            </div>
            {% endfor %}
        </fieldset>
        <input class="button" type="submit" value="Vote">
    </form>

    <p><a class="button" href="{% url 'polls:results' question.id %}">Results</a></p>

    <p><a class="button" href="{% url 'polls:index' %}">Back to List of Polls</a></p>
{% endblock content %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
    <section class="sec-index">
        <ul>
        {% if user.is_authenticated %}
            <p class="text-p">Welcome back, <b>{{user.username}}</b>.</p>
        {% else %}
            <p class="text-p">Please <a class="button" href="{% url 'login' %}?next={{request.path}}">Login</a> to vote.</p>
        {% endif %}
        </ul>
        {% if latest_question_list %}
            <ul class="question-box-list">
            {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                <a class="button" href="{% url 'polls:results' question.id %}">Results</a>
            </li>
            {% endfor %}
            </ul>
        {% else %}
            <p class="text-p">No polls are available.</p>
        {% endif %}
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <b><p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p></b>
            {% endfor %}
        </ul>
        {% endif %}
    </section>
{% endblock content %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block title %}<title>Poll Results</title>{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    <table class="result-table">
        <thead>
            <tr>
                <th>Choice</th>
                <th>Votes</th>
            </tr>
        </thead>
        <tbody>
            {% for choice in question.choice_set.all %}
                <tr>
                    <td>{{ choice.choice_text }}</td>
                    <td>{{ choice.votes }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <b><p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p></b>
        {% endfor %}
    </ul>
    {% endif %}

    <p><a class="button" href="{% url 'polls:index' %}">Back to List of Polls</a></p>
{% endblock content %}